# Generated by Django 4.2 on 2024-05-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0004_rename_materias_mate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mate',
            name='profesor',
            field=models.CharField(default='prof', max_length=30),
        ),
    ]
