# Generated by Django 4.2 on 2024-05-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0005_mate_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mate',
            name='profesor',
        ),
    ]
