# Generated by Django 4.2 on 2024-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0007_alter_estu_id_alter_mate_id_alter_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estu',
            name='id',
            field=models.AutoField(db_column='user_estu', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mate',
            name='id',
            field=models.AutoField(db_column='user_mate', primary_key=True, serialize=False),
        ),
    ]
