# Generated by Django 4.2 on 2024-05-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0009_alter_estu_id_alter_mate_id_alter_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estu',
            name='id',
            field=models.AutoField(db_column='appcolegio_estu', primary_key=True, serialize=False),
        ),
    ]
