# Generated by Django 4.2 on 2024-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0011_alter_curso_id_alter_estu_id_alter_mate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alum',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
