# Generated by Django 4.2 on 2024-05-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0012_alum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estu',
            table='estu',
        ),
    ]
