# Generated by Django 4.2 on 2024-05-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0013_alter_estu_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alum',
            table='Alumnos',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Cursos',
        ),
        migrations.AlterModelTable(
            name='estu',
            table='Estudiantes',
        ),
        migrations.AlterModelTable(
            name='mate',
            table='Materias',
        ),
        migrations.AlterModelTable(
            name='prof',
            table='Profesores',
        ),
    ]
