# Generated by Django 4.2 on 2024-05-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0014_alter_alum_table_alter_curso_table_alter_estu_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mate',
            options={'verbose_name': 'Materias'},
        ),
    ]
