# Generated by Django 4.2 on 2024-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0015_alter_mate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
