# Generated by Django 4.2 on 2024-05-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0016_alter_mate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mate',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcolegio.prof'),
        ),
    ]
