# Generated by Django 4.2 on 2024-05-14 17:04

import appcolegio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0019_mate_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='Profesores',
            field=models.CharField(choices=[('Profesor', appcolegio.models.prof), ('2', 'pedro')], default='1', max_length=30),
        ),
    ]
