# Generated by Django 4.2 on 2024-05-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0020_alter_mate_profesores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mate',
            name='Profesores',
        ),
    ]
