# Generated by Django 4.2 on 2024-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0021_remove_mate_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(max_length=10),
        ),
    ]
