# Generated by Django 4.2 on 2024-05-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0022_alter_curso_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='mate',
            name='cursos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcolegio.curso'),
        ),
    ]
