# Generated by Django 4.2 on 2024-05-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0023_mate_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mate',
            name='cursos',
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cursos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcolegio.curso')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcolegio.mate')),
            ],
        ),
    ]
