# Generated by Django 4.2 on 2024-06-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0024_remove_mate_cursos_cursomateria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mate',
            options={},
        ),
        migrations.AlterField(
            model_name='cursomateria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='cursomateria',
            table='CursoMateria',
        ),
    ]
